// Used if user inputs state code instead of state name. Dictionary generated
// using ChatGPT. Not complete: some state codes missing. Wrote a Python program
// to get rid of duplicates.
const stateCodesMap = {
    // United States
    "AL": "alabama",
    "AK": "alaska",
    "AZ": "arizona",
    "AR": "arkansas",
    "CA": "california",
    "CO": "colorado",
    "CT": "connecticut",
    "DE": "delaware",
    "FL": "florida",
    "GA": "georgia",
    "HI": "hawaii",
    "ID": "idaho",
    "IL": "illinois",
    "IN": "indiana",
    "IA": "iowa",
    "KS": "kansas",
    "KY": "kentucky",
    "LA": "louisiana",
    "ME": "maine",
    "MD": "maryland",
    "MA": "massachusetts",
    "MI": "michigan",
    "MN": "minnesota",
    "MS": "mississippi",
    "MO": "missouri",
    "MT": "montana",
    "NE": "nebraska",
    "NV": "nevada",
    "NH": "new hampshire",
    "NJ": "new jersey",
    "NM": "new mexico",
    "NY": "new york",
    "NC": "north carolina",
    "ND": "north dakota",
    "OH": "ohio",
    "OK": "oklahoma",
    "OR": "oregon",
    "PA": "pennsylvania",
    "RI": "rhode island",
    "SC": "south carolina",
    "SD": "south dakota",
    "TN": "tennessee",
    "TX": "texas",
    "UT": "utah",
    "VT": "vermont",
    "VA": "virginia",
    "WA": "washington",
    "WV": "west virginia",
    "WI": "wisconsin",
    "WY": "wyoming",

    // Canada
    "AB": "alberta",
    "BC": "british columbia",
    "MB": "manitoba",
    "NB": "new brunswick",
    "NL": "newfoundland and labrador",
    "NS": "nova scotia",
    "ON": "ontario",
    "PE": "prince edward island",
    "QC": "quebec",
    "SK": "saskatchewan",

    // India
    "AP": "andhra pradesh",
    "AS": "assam",
    "BR": "bihar",
    "GJ": "gujarat",
    "HR": "haryana",
    "HP": "himachal pradesh",
    "JK": "jammu and kashmir",
    "JH": "jharkhand",
    "KA": "karnataka",
    "KL": "kerala",
    "MP": "madhya pradesh",
    "MH": "maharashtra",
    "ML": "meghalaya",
    "MZ": "mizoram",
    "PB": "punjab",
    "RJ": "rajasthan",
    "TG": "telangana",
    "TR": "tripura",
    "UP": "uttar pradesh",
    "WB": "west bengal",

    // Australia
    "ACT": "australian capital territory",
    "NSW": "new south wales",
    "NT": "northern territory",
    "QLD": "queensland",
    "SA": "south australia",
    "TAS": "tasmania",
    "VIC": "victoria",

    // Germany
    "BW": "baden-wurttemberg",
    "BY": "bavaria",
    "BE": "berlin",
    "BB": "brandenburg",
    "HB": "bremen",
    "HH": "hamburg",
    "HE": "hesse",
    "MV": "mecklenburg-vorpommern",
    "NI": "lower saxony",
    "NW": "north rhine-westphalia",
    "RP": "rhineland-palatinate",
    "SL": "saarland",
    "SN": "saxony",
    "ST": "saxony-anhalt",
    "SH": "schleswig-holstein",
    "TH": "thuringia",

    // Brazil
    "AC": "acre",
    "AM": "amazonas",
    "BA": "bahia",
    "CE": "ceara",
    "DF": "distrito federal",
    "ES": "espirito santo",
    "GO": "goias",
    "MG": "minas gerais",
    "PR": "parana",
    "PI": "piaui",
    "RN": "rio grande do norte",
    "RS": "rio grande do sul",
    "RO": "rondonia",
    "RR": "roraima",
    "SP": "sao paulo",
    "SE": "sergipe",
    "TO": "tocantins",

    // China
    "AH": "anhui",
    "BJ": "beijing",
    "CQ": "chongqing",
    "FJ": "fujian",
    "GS": "gansu",
    "GD": "guangdong",
    "GX": "guangxi",
    "GZ": "guizhou",
    "HL": "heilongjiang",
    "HA": "henan",
    "HK": "hong kong",
    "HN": "hunan",
    "JS": "jiangsu",
    "JX": "jiangxi",
    "JL": "jilin",
    "LN": "liaoning",
    "NX": "ningxia",
    "QH": "qinghai",
    "SX": "shanxi",
    "TW": "taiwan",
    "TJ": "tianjin",
    "XZ": "tibet",
    "XJ": "xinjiang",
    "YN": "yunnan",
    "ZJ": "zhejiang",

    // Russia
    "AD": "adygea",
    "BU": "buryatia",
    "CU": "chuvashia",
    "DA": "dagestan",
    "KB": "kabardino-balkaria",
    "KC": "karachay-cherkessia",
    "KR": "karelia",
    "KO": "komi",
    "TA": "tatarstan",
    "TY": "tuva",
    "UD": "udmurtia",
    "ALT": "altai krai",
    "KAM": "kamchatka krai",
    "KHA": "khabarovsk krai",
    "KDA": "krasnodar krai",
    "KYA": "krasnoyarsk krai",
    "PER": "perm krai",
    "PRI": "primorsky krai",
    "STA": "stavropol krai",
    "ZAB": "zabaykalsky krai",
    "AMU": "amur oblast",
    "ARK": "arkhangelsk oblast",
    "AST": "astrakhan oblast",
    "BEL": "belgorod oblast",
    "BRY": "bryansk oblast",
    "CHE": "chelyabinsk oblast",
    "IRK": "irkutsk oblast",
    "IVA": "ivanovo oblast",
    "KGD": "kaliningrad oblast",
    "KLU": "kaluga oblast",
    "KEM": "kemerovo oblast",
    "KIR": "kirov oblast",
    "KOS": "kostroma oblast",
    "KGN": "kurgan oblast",
    "KRS": "kursk oblast",
    "LEN": "leningrad oblast",
    "LIP": "lipetsk oblast",
    "MAG": "magadan oblast",
    "MOS": "moscow oblast",
    "MUR": "murmansk oblast",
    "NIZ": "nizhny novgorod oblast",
    "NGR": "novgorod oblast",
    "NVS": "novosibirsk oblast",
    "OMS": "omsk oblast",
    "ORE": "orenburg oblast",
    "ORL": "orel oblast",
    "PNZ": "penza oblast",
    "PSK": "pskov oblast",
    "ROS": "rostov oblast",
    "RYA": "ryazan oblast",
    "SAK": "sakhalin oblast",
    "SAM": "samara oblast",
    "SAR": "saratov oblast",
    "SMO": "smolensk oblast",
    "SVE": "sverdlovsk oblast",
    "TAM": "tambov oblast",
    "TOM": "tomsk oblast",
    "TUL": "tula oblast",
    "TVE": "tver oblast",
    "TYU": "tyumen oblast",
    "ULY": "ulyanovsk oblast",
    "VLA": "vladimir oblast",
    "VGG": "volgograd oblast",
    "VLG": "vologda oblast",
    "VOR": "voronezh oblast",
    "YAN": "yamalo-nenets autonomous okrug",
    "YAR": "yaroslavl oblast",
    "CHU": "chukotka autonomous okrug",
    "EVE": "evenkia",
    "KHM": "khanty-mansi autonomous okrug",
    "KOR": "koryakia",
    "YEV": "jewish autonomous oblast"
}

export default stateCodesMap;
