// Used if user inputs state code instead of state name. Dictionary generated
// using ChatGPT. Not complete: many state codes missing. Wrote a Python program
// to get rid of duplicates.
const stateCodesMap = {
    // United States
    "AL": ["alabama", "united states"],
    "AK": ["alaska", "united states"],
    "AZ": ["arizona", "united states"],
    "AR": ["arkansas", "united states"],
    "CA": ["california", "united states"],
    "CO": ["colorado", "united states"],
    "CT": ["connecticut", "united states"],
    "DE": ["delaware", "united states"],
    "FL": ["florida", "united states"],
    "GA": ["georgia", "united states"],
    "HI": ["hawaii", "united states"],
    "ID": ["idaho", "united states"],
    "IL": ["illinois", "united states"],
    "IN": ["indiana", "united states"],
    "IA": ["iowa", "united states"],
    "KS": ["kansas", "united states"],
    "KY": ["kentucky", "united states"],
    "LA": ["louisiana", "united states"],
    "ME": ["maine", "united states"],
    "MD": ["maryland", "united states"],
    "MA": ["massachusetts", "united states"],
    "MI": ["michigan", "united states"],
    "MN": ["minnesota", "united states"],
    "MS": ["mississippi", "united states"],
    "MO": ["missouri", "united states"],
    "MT": ["montana", "united states"],
    "NE": ["nebraska", "united states"],
    "NV": ["nevada", "united states"],
    "NH": ["new hampshire", "united states"],
    "NJ": ["new jersey", "united states"],
    "NM": ["new mexico", "united states"],
    "NY": ["new york", "united states"],
    "NC": ["north carolina", "united states"],
    "ND": ["north dakota", "united states"],
    "OH": ["ohio", "united states"],
    "OK": ["oklahoma", "united states"],
    "OR": ["oregon", "united states"],
    "PA": ["pennsylvania", "united states"],
    "RI": ["rhode island", "united states"],
    "SC": ["south carolina", "united states"],
    "SD": ["south dakota", "united states"],
    "TN": ["tennessee", "united states"],
    "TX": ["texas", "united states"],
    "UT": ["utah", "united states"],
    "VT": ["vermont", "united states"],
    "VA": ["virginia", "united states"],
    "WA": ["washington", "united states"],
    "WV": ["west virginia", "united states"],
    "WI": ["wisconsin", "united states"],
    "WY": ["wyoming", "united states"],

    // Canada
    "AB": ["alberta", "canada"],
    "BC": ["british columbia", "canada"],
    "MB": ["manitoba", "canada"],
    "NB": ["new brunswick", "canada"],
    "NL": ["newfoundland and labrador", "canada"],
    "NS": ["nova scotia", "canada"],
    "ON": ["ontario", "canada"],
    "PE": ["prince edward island", "canada"],
    "QC": ["quebec", "canada"],
    "SK": ["saskatchewan", "canada"],

    // India
    "AP": ["andhra pradesh", "india"],
    "AS": ["assam", "india"],
    "BR": ["bihar", "india"],
    "GJ": ["gujarat", "india"],
    "HR": ["haryana", "india"],
    "HP": ["himachal pradesh", "india"],
    "JK": ["jammu and kashmir", "india"],
    "JH": ["jharkhand", "india"],
    "KA": ["karnataka", "india"],
    "KL": ["kerala", "india"],
    "MP": ["madhya pradesh", "india"],
    "MH": ["maharashtra", "india"],
    "ML": ["meghalaya", "india"],
    "MZ": ["mizoram", "india"],
    "PB": ["punjab", "india"],
    "RJ": ["rajasthan", "india"],
    "TG": ["telangana", "india"],
    "TR": ["tripura", "india"],
    "UP": ["uttar pradesh", "india"],
    "WB": ["west bengal", "india"],

    // Australia
    "ACT": ["australian capital territory", "australia"],
    "NSW": ["new south wales", "australia"],
    "NT": ["northern territory", "australia"],
    "QLD": ["queensland", "australia"],
    "SA": ["south australia", "australia"],
    "TAS": ["tasmania", "australia"],
    "VIC": ["victoria", "australia"],

    // Germany
    "BW": ["baden-wurttemberg", "germany"],
    "BY": ["bavaria", "germany"],
    "BE": ["berlin", "germany"],
    "BB": ["brandenburg", "germany"],
    "HB": ["bremen", "germany"],
    "HH": ["hamburg", "germany"],
    "HE": ["hesse", "germany"],
    "MV": ["mecklenburg-vorpommern", "germany"],
    "NI": ["lower saxony", "germany"],
    "NW": ["north rhine-westphalia", "germany"],
    "RP": ["rhineland-palatinate", "germany"],
    "SL": ["saarland", "germany"],
    "SN": ["saxony", "germany"],
    "ST": ["saxony-anhalt", "germany"],
    "SH": ["schleswig-holstein", "germany"],
    "TH": ["thuringia", "germany"],

    // Brazil
    "AC": ["acre", "brazil"],
    "AM": ["amazonas", "brazil"],
    "BA": ["bahia", "brazil"],
    "CE": ["ceara", "brazil"],
    "DF": ["distrito federal", "brazil"],
    "ES": ["espirito santo", "brazil"],
    "GO": ["goias", "brazil"],
    "MG": ["minas gerais", "brazil"],
    "PR": ["parana", "brazil"],
    "PI": ["piaui", "brazil"],
    "RN": ["rio grande do norte", "brazil"],
    "RS": ["rio grande do sul", "brazil"],
    "RO": ["rondonia", "brazil"],
    "RR": ["roraima", "brazil"],
    "SP": ["sao paulo", "brazil"],
    "SE": ["sergipe", "brazil"],
    "TO": ["tocantins", "brazil"],

    // China
    "AH": ["anhui", "china"],
    "BJ": ["beijing", "china"],
    "CQ": ["chongqing", "china"],
    "FJ": ["fujian", "china"],
    "GS": ["gansu", "china"],
    "GD": ["guangdong", "china"],
    "GX": ["guangxi", "china"],
    "GZ": ["guizhou", "china"],
    "HL": ["heilongjiang", "china"],
    "HA": ["henan", "china"],
    "HK": ["hong kong", "china"],
    "HN": ["hunan", "china"],
    "JS": ["jiangsu", "china"],
    "JX": ["jiangxi", "china"],
    "JL": ["jilin", "china"],
    "LN": ["liaoning", "china"],
    "NX": ["ningxia", "china"],
    "QH": ["qinghai", "china"],
    "SX": ["shanxi", "china"],
    "TW": ["taiwan", "china"],
    "TJ": ["tianjin", "china"],
    "XZ": ["tibet", "china"],
    "XJ": ["xinjiang", "china"],
    "YN": ["yunnan", "china"],
    "ZJ": ["zhejiang", "china"],

    // Russia
    "AD": ["adygea", "russia"],
    "BU": ["buryatia", "russia"],
    "CU": ["chuvashia", "russia"],
    "DA": ["dagestan", "russia"],
    "KB": ["kabardino-balkaria", "russia"],
    "KC": ["karachay-cherkessia", "russia"],
    "KR": ["karelia", "russia"],
    "KO": ["komi", "russia"],
    "TA": ["tatarstan", "russia"],
    "TY": ["tuva", "russia"],
    "UD": ["udmurtia", "russia"],
    "ALT": ["altai krai", "russia"],
    "KAM": ["kamchatka krai", "russia"],
    "KHA": ["khabarovsk krai", "russia"],
    "KDA": ["krasnodar krai", "russia"],
    "KYA": ["krasnoyarsk krai", "russia"],
    "PER": ["perm krai", "russia"],
    "PRI": ["primorsky krai", "russia"],
    "STA": ["stavropol krai", "russia"],
    "ZAB": ["zabaykalsky krai", "russia"],
    "AMU": ["amur oblast", "russia"],
    "ARK": ["arkhangelsk oblast", "russia"],
    "AST": ["astrakhan oblast", "russia"],
    "BEL": ["belgorod oblast", "russia"],
    "BRY": ["bryansk oblast", "russia"],
    "CHE": ["chelyabinsk oblast", "russia"],
    "IRK": ["irkutsk oblast", "russia"],
    "IVA": ["ivanovo oblast", "russia"],
    "KGD": ["kaliningrad oblast", "russia"],
    "KLU": ["kaluga oblast", "russia"],
    "KEM": ["kemerovo oblast", "russia"],
    "KIR": ["kirov oblast", "russia"],
    "KOS": ["kostroma oblast", "russia"],
    "KGN": ["kurgan oblast", "russia"],
    "KRS": ["kursk oblast", "russia"],
    "LEN": ["leningrad oblast", "russia"],
    "LIP": ["lipetsk oblast", "russia"],
    "MAG": ["magadan oblast", "russia"],
    "MOS": ["moscow oblast", "russia"],
    "MUR": ["murmansk oblast", "russia"],
    "NIZ": ["nizhny novgorod oblast", "russia"],
    "NGR": ["novgorod oblast", "russia"],
    "NVS": ["novosibirsk oblast", "russia"],
    "OMS": ["omsk oblast", "russia"],
    "ORE": ["orenburg oblast", "russia"],
    "ORL": ["orel oblast", "russia"],
    "PNZ": ["penza oblast", "russia"],
    "PSK": ["pskov oblast", "russia"],
    "ROS": ["rostov oblast", "russia"],
    "RYA": ["ryazan oblast", "russia"],
    "SAK": ["sakhalin oblast", "russia"],
    "SAM": ["samara oblast", "russia"],
    "SAR": ["saratov oblast", "russia"],
    "SMO": ["smolensk oblast", "russia"],
    "SVE": ["sverdlovsk oblast", "russia"],
    "TAM": ["tambov oblast", "russia"],
    "TOM": ["tomsk oblast", "russia"],
    "TUL": ["tula oblast", "russia"],
    "TVE": ["tver oblast", "russia"],
    "TYU": ["tyumen oblast", "russia"],
    "ULY": ["ulyanovsk oblast", "russia"],
    "VLA": ["vladimir oblast", "russia"],
    "VGG": ["volgograd oblast", "russia"],
    "VLG": ["vologda oblast", "russia"],
    "VOR": ["voronezh oblast", "russia"],
    "YAN": ["yamalo-nenets autonomous okrug", "russia"],
    "YAR": ["yaroslavl oblast", "russia"],
    "CHU": ["chukotka autonomous okrug", "russia"],
    "EVE": ["evenkia", "russia"],
    "KHM": ["khanty-mansi autonomous okrug", "russia"],
    "KOR": ["koryakia", "russia"],
    "YEV": ["jewish autonomous oblast", "russia"]
}

export default stateCodesMap;
